### ISSUE TITLE
choose which plancton classes we are interested in

### ISSUE THREAD

**Issue by ldocao** [ldocao/planktidex#4]
idéalement: trouver quelques sous classes de plancton qui sont très distinctes visuellement, de la meme taille, et pour lesquelles on a beaucoup d'exemples

**Comment by AFanny** [comment]
The different class used to label the images were not real "class" when you consider the biological meaning. Sometimes names were given by the shape of the organism on the picture, apparently because this lead to changes in their behaviour (https://www.kaggle.com/c/datasciencebowl/data)
To simplify at the beginning, we pulled the different folders which contain the same classes in one folder labelled as the exact class name. 
I addition, some classes were not classes but order, family or something else (notice that using http://www.marinespecies.org ).. That's why we put all the classification name as folder label.
